### ISSUE TITLE
Controlevragen over Wbni opnemen

### ISSUE THREAD

**Issue by eric-nieuwland** [ICTU/Kwaliteitsaanpak#101]
De Wbni verplicht bepaalde dienstverleners afdoende beveiligingsmaatregelen te treffen.
Deze maatregelen kunnen zowel procedureel als technisch van aard zijn.
Wanneer ze technisch van aard zijn, moeten ze (mogelijk) (ook) in software gerealiseerd worden.
De proceseigenaar (=opdrachtgever) is verantwoordelijk, maar de softwareontwikkelaar zou vanuit professionaliteit ook naar toepasselijkheid van de Wbni en de daaruit voortvloeiende maatregelen moeten vragen.

Graag deze controlevraag opnemen in de kwaliteitsaanpak.

**Comment by fniessink** [comment]
@eric-nieuwland, omdat we voor andere bronnen zoals BIR en SSD ook geen controlevragen hebben, heb ik dat voor de Wbni ook niet gedaan, maar de Wet alleen genoemd als mogelijke bron. Zie PR #108. Omdat de Wet en het bijbehorende besluit op dit moment geen enkele concrete technische maatregel noemen lijkt me dat wel voldoende zo. Eens?
