### ISSUE TITLE
Opnemen in KA dat projecten structureel tijd besteden aan/vrijhouden voor oplossen technische schuld

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#118]
Bij de meeste projecten ligt de nadruk op het realiseren van functionaliteit, waar het oplossen van Technical Debt ook waarde heeft. De 20% regel is bedacht om ervoor te zorgen dat de verhouding in stories die in de sprint getrokken worden beter wordt. M.a.w. 20% van de stories moet een Technical Debt Story zijn.
 
Bij het Nationaal Archief wordt hiervoor een apart project bijgehouden, zodat in Jira goed te zien is of iets een TD of een Functionele story is.
 
Door het hier bij te houden is het ook mogelijk hier bevragingen over te doen, zodat men op cijfers gebaseerd kan sturen als blijkt dat TD of functioneel te veel de overhand krijgt.

-- @arreu

**Comment by fniessink** [comment]
We moeten eigenlijk inventariseren bij welke projecten die hoe structureel wordt toegepast.

**Comment by fniessink** [comment]
Naast planmatig aanpakken moet er ook structureel tijd worden vrijgemaakt hiervoor. (Alles in de laatste sprint oplossen is ook "planmatig").

**Comment by arreu** [comment]
eens.


Arjen Reudink
Scrummaster Nationaal Archief (ma-middag/wo/do-middag/vr)
Scrummaster ICTU Bedrijfsvoering (ma-ochtend/di/do-ochtend)

Softwarerealisatie | ICTU
T +31 (0)6 218 87 530
E arjen.reudink@ictu.nl
I www.ictu.nl<http://www.ictu.nl>

"Van overzicht via inzicht naar veranderingverbetering"
Wilhelmina van Pruisenweg 104
2595 AN Den Haag
Postbus 84011
2508 AA  DEN HAAG
ICTU werkt aan een betere digitale overheid
________________________________
