### ISSUE TITLE
BIO verwerken in Kwaliteitsaanpak

### ISSUE THREAD

**Issue by denniebouman** [ICTU/Kwaliteitsaanpak#122]

**Comment by fniessink** [comment]
@denniebouman Wat is het doel hiervan? Wil je kunnen aantonen dat de KA BIO-compliant is? Wie vraagt dat?

**Comment by denniebouman** [comment]
@fniessink 
Vanaf 1 januari 2020 is de Baseline Informatiebeveiliging Overheid (BIO) van kracht. De BIO vervangt de bestaande baselines informatieveiligheid voor Gemeenten, Rijk, Waterschappen en Provincies. Van BIG, BIR, BIR2017, IBI en BIWA naar BIO. 

In de huidige Kwaliteitsaanpak wordt verwezen naar de BIR (2017) welke vanaf 2020 dus niet meer geldt (2019 = overgangsjaar).

**Comment by fniessink** [comment]
NFE-template H7.1 ook aanpassen
