### ISSUE TITLE
Geel gemarkeerde instructies kunnen niet met de markeerstift in Word worden aangepast 

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#163]
@Barleduc De instructies zijn een stijl en dus werkt het verwijderen van de markering niet. Je moet de stijl aanpassen. Dat is voor gebruikers onverwacht. Kunnen we de instructiestijl vervangen door een "echte" gele markering?

**Comment by Barleduc** [comment]
In de nieuwe .Net-versie van de generator is dit opgelost. Die wordt binnenkort toegevoegd en getest.
