### ISSUE TITLE
Geen productiegegevens voor testen

### ISSUE THREAD

**Issue by eric-nieuwland** [ICTU/Kwaliteitsaanpak#166]
Het template voor testen geeft al aan dat na een test de daarvoor gebruikte gegevens weer verwijderd worden.
Het lijkt me een goed idee ergens (een maatregel?) expliciet te vermelden dat ten behoeve van de softwareontwikkeling zelf geen gebruik gemaakt wordt van productiegegevens.
Voor het werken met productiegegevens is een strikt gescheiden omgeving nodig, die als productieomgeving geldt, is ingericht en wordt beheerd.

**Comment by fniessink** [comment]
@eric-nieuwland Wat kunnen we gebruiken als bron voor deze randvoorwaarde/eis/maatregel?

**Comment by eric-nieuwland** [comment]
BIO
- 12.01.04
- 14.03
