### ISSUE TITLE
M15 aanscherpen

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#298]
Verduidelijken hoe een project deze maatregel kan beoordelen bij een self-assessment. Zeker omdat ICTU een mix biedt van closed en open source oplossingen.

Maatregel niet in termen van "voorkeur" formuleren.

Refereren aan Kamerbrief: https://www.rijksoverheid.nl/documenten/kamerstukken/2020/04/17/kamerbrief-inzake-vrijgeven-broncode-overheidssoftware

Opnemen in voorfase dat er niet alleen een afweging gemaakt moet zijn tussen make-or-buy, maar ook tussen open en closed source. Zorgen dat er een expliciete rationale is. Keuze kan wellicht ook verschillen per component.

Door bij elke maatregel een vraag te definieren en die te gebruiken in de self-assessment (ipv alleen de maatregeltitels) kan het wellicht makkelijker worden voor projecten om de ICTU-brede maatregelen te scoren.

**Comment by AukeBloembergen** [comment]
We moeten ook duidelijk maken op welke software de maatregel betrekking heeft:
- Hoofdstuk 8 gaat over wat het project van ICTU krijgt: tooling. De keuzes worden dus door ICTU gemaakt, niet door het project.
- Als we iets willen zeggen over de op te leveren applicatie als open source: moet dat dan in een aparte maatregel?
