### ISSUE TITLE
Voorwaarden opschrijven voor het alleen door de OG laten uitvoeren van de periodieke beveiligingstest

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#300]
- ICTU laat altijd de tools meedraaien in de pijplijn, dat is een gegeven
- Als de OG de beveiligingstest laat uitvoeren ontvangt ICTU de beveiligingstestrapportage
- ICTU (kwaliteitsmanager)bewaakt de periodiciteit (reminder in Quality-time)
- ICTU en OG checken in voorfase dat OG de benodigde contractuele mogelijkheden heeft een beveiligingstest in te kopen

Bovenstaande zaken zouden analoog voor toegankelijkheid kunnen gelden.

**Comment by AukeBloembergen** [comment]
We hebben ook besproken wat ICTU zelf kan doen:
- Security-audit op de code;
- Pentest in OT-omgeving van ICTU.

Als in de voorfase blijkt dat OG geen beveiligingstest wil laten uitvoeren dan zal ICTU zelf een testplan maken (onze verantwoordelijkheid als overheidsleverancier). De dan uit te voeren tests zijn voor rekening van OG, en hierover zal dus onderhandeld moeten worden. Om die reden moeten we streven naar zo efficiënt mogelijke uitvoering van deze tests.
