### ISSUE TITLE
Voorwaarden opschrijven voor het alleen door de OG laten uitvoeren van de performancetest

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#301]
Ideale situatie:

- OG voert frequent een performancetest uit (liefst elke sprint)
- OG deelt resultaten met ICTU
- Testomgeving is representatief voor productie
- Testdata is representatief voor productie
- Belasting is representatief voor productie
- ICTU en OG checken in voorfase dat OG de benodigde contractuele mogelijkheden heeft een performancetest in te kopen
- ICTU (kwaliteitsmanager)bewaakt de periodiciteit (reminder in Quality-time)

Als niet aan alle voorwaarden kan worden voldaan door OG, en de NFE voor performance zijn wel belangrijk, richt ICTU zelf een regressieperformancetest in.

En wat doen we met duurtesten en stresstesten.

**Comment by AukeBloembergen** [comment]
Wat moet in Voorstel en overeenkomst worden opgenomen over de uitvoering en kosten van het performancetesten door ICTU?

**Comment by fniessink** [comment]
Uit self-assessment 2021: "Performancetests
Meningen zijn verdeeld over noodzaak en frequentie van tests door ICTU in de eigen ontwikkelstraat. Handreiking bieden voor discussie over zelf doen versus beheerpartij/OG die het doet en wanneer dat evt. “goed genoeg” is als vervanging van performancetesten bij/door ICTU. Moet/mag het project zijn eigen normen stellen, op basis van omgeving, releasetempo, enz?
Er is behoefte aan heldere definities van soorten performancetests.
Geïnteresseerd in dit onderwerp zijn Tom, Wigle, Dennie, Deli(?).
Conclusie update KA en Kwaliteitsplan: Handreiking voor discussie (zie hierboven) incl. definities van soorten performancetests. Daarna impact op vergelijkbare tests (security) bekijken."
