### ISSUE TITLE
Manifest verwijderen uit Kwaliteitsaanpak

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#370]
Manifest voegt weinig toe dat ook niet al op andere plekken staat. Scheelt H2 en bijlage A (2,5 A4). @AukeBloembergen, wat vind jij?

**Comment by AukeBloembergen** [comment]
Eens Frank. Met een kleine aanvulling in de inleiding (hieronder vetgedrukt) zijn alle onderwerpen van het manifest al genoemd. En bijlage A is niet nodig. De lezer kan zelf wel constateren hoe de doelstellingen in de KA worden ingevuld.

ICTU is ervan overtuigd dat het bouwen van software die goed aansluit bij de behoeften van gebruikers en andere belanghebbenden en die ook na oplevering nog goed te onderhouden is, bijdraagt aan betere informatiesystemen en een betere dienstverlening binnen en buiten de overheid. **Daarom hangt ICTU het agile werken bij de overheid aan, waarbij wij samen met de opdrachtgever werken aan passende oplossingen.** Die dienstverlening moet bovendien betrouwbaar zijn voor burgers, bedrijven en ambtenaren. Daarom besteedt ICTU altijd expliciet aandacht aan zaken die die betrouwbaarheid beïnvloeden, zoals beveiliging, privacy, performance en toegankelijkheid. De Kwaliteitsaanpak dient daarvoor als leidraad, maar de aanpak voorziet ook in mogelijkheden om het project en het eindproduct aan te passen aan de specifieke situatie.
