### ISSUE TITLE
Maatregel toevoegen voor software-overdracht

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#492]
Voeg een maatregel toe voor overdracht van de software aan een derde partij die het onderhoud en/of doorontwikkeling gaat doen. Baseer de maatregel op NPR5325.

**Comment by AukeBloembergen** [comment]
O.a. op verzoek van Marjolein en Aziz

**Comment by fniessink** [comment]
Voeg een maatregel toe voor overdracht van de software aan een derde partij die het onderhoud en/of doorontwikkeling gaat doen. Baseer de maatregel op NPR5325.
