### ISSUE TITLE
Tekst reviewen op generaliseerbaarheid DevOps

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#560]
De huidige tekst is sterk geent op softwareontwikkeling. Kunnen we ter voorbereiding op toevoeging van DevOps alvast aanpassingen maken die die toevoeging makkelijker gaan maken.

**Comment by fniessink** [comment]
@AukeBloembergen Ik zie niet direct aanpassingen die we beter van tevoren kunnen maken.

**Comment by AukeBloembergen** [comment]
Dank Frank. Dan ga ik aan de slag.
