### ISSUE TITLE
Codekwaliteit - werkwijze reviews

### ISSUE THREAD

**Issue by AukeBloembergen** [ICTU/Kwaliteitsaanpak#574]
3 okt 22 in Inhoudelijke overleg. Onderdelen van de werkwijze om de codekwaliteit te borgen zijn:
- [x] de aspecten van de codekwaliteit die geautomatiseerd kunnen worden gemeten in QT
- [x] Handmatige reviews
   - [x]  Peer reviews: als eis opnemen in DoD; ondersteunen in Quality-time (niet: Jira)
   - [x] Externe reviews zoals SIG (deze kunnen in MTP worden beschreven)
- [x] Begin met de ontwikkelstandaard vast te leggen in het SAD (aldus Steven). Denk aan verdeling van de business-logica over frontend en backend. => zit al in SAD-template in het hoofdstuk "Implementatierichtlijnen".
- [x] Gebruik tooling voor de opmaak van code, zie #601.

**Comment by fniessink** [comment]
KP-template aanscherpen:
- Broncode reviews niet in MTP opnemen maar in KP zelf.
- Niet zeggen dat het project "afspraken maakt", maar gewoon de afspraken vastleggen in het KP(-template).
