### ISSUE TITLE
Vrijgaveadvies niet meer alleen verantwoordelijkheid ICTU

### ISSUE THREAD

**Issue by AukeBloembergen** [ICTU/Kwaliteitsaanpak#576]
Vrijgaveadvies is in de meeste projecten impliciet: het opleveren van een release betekent dat het advies van ICTU positief is. Het vrijgaveadvies lijkt ook een minder relevant document bij agile werken. Project als geheel moet het vrijgaveadvies doen en ICTU zou alleen input aan het vrijgaveadvies moeten leveren. Deze de facto werkwijze zal als standaard worden beschreven in de KA.
(Gezamenlijke self assessments 2022)

**Comment by AukeBloembergen** [comment]
Ha Marisca,

Ik zou uitzoeken hoe binnen ICTU wordt omgegaan met het formeel goedkeuren van een release voor productie.

Inmiddels heb ik er met een sdm’er en een PL over gesproken. Met als conclusie:

•	ICTU draagt een release over met een vrijgave-advies en documentatie.
•	Hiervoor krijgt ICTU van de opdrachtgever een formeel akkoord. 
•	Op dat moment gaat ICTU ervan uit dat zonder tegenbericht de release in productie zal worden genomen.
•	Het testen en goedkeuren (toestemming geven) voor productie is een verantwoordelijkheid van de opdrachtgever, en gebeurt ook binnen diens organisatie.
•	Als dit - bij uitzondering – leidt tot het verzoek aan ICTU om de release te herstellen worden nadere afspraken gemaakt, die ook worden vastgelegd.
•	Zijn deze afspraken er niet, dan is er blijkbaar geen probleem: “geen bericht, goed bericht”.

**Comment by fniessink** [comment]
Tekst over vrijgaveadvies aangescherpt als onderdeel van het aanscherpen van de rollen.
