### ISSUE TITLE
Handreikingen toevoegen voor het voldoen aan de NFE's 

### ISSUE THREAD

**Issue by AukeBloembergen** [ICTU/Kwaliteitsaanpak#605]
Uit overleg Auke, Dennie en Sebastiaan (21 nov ’22 en 7 feb '23)

### KA

- [x] Verantwoordelijkheden OG, ICTU, beheerpartij voor de verschillende documenten zijn beschreven aan het einde van M01. Maar aan het begin staat: “Opdrachtgever, ICTU, beheerpartij en andere meewerkende partijen, leveren samen de onderstaande informatie op.” Dat is misleidend. Liever hier vooruit verwijzen naar paragraaf Verantwoordelijkheden.
- [x] Laten we – in M02 - nog iets zeggen over hoe NFE’s worden opgevolgd.
Een deel van de NFE's kan worden ingevuld in de software zelf:
- oplossingen die via de backlog worden gerealiseerd zijn onderdeel van de reguliere tests
- overige oplossingen worden vastgelegd in het SAD; deze kunnen gedeeltelijk worden bewaakt in QT.

Een ander deel van de NFE's, zoals de beschikbaarheid van de software voor de gebruikers, kan alleen in de productie(omgeving) worden ingevuld. Bij een DevOps-werkwijze is dit ook de verantwoordelijkheid van het project.

Vervolgens toevoegen bij "Kwaliteitseigenschappen van de software die niet (volledig) geautomatiseerd kunnen worden gemeten": De NFE's worden periodiek doorgenomen door de kwaliteitsmanager en het ontwikkelteam (lead developer, tester, ...). Hierbij wordt besproken hoe ze in de software zijn verwerkt, hoe het team dit heeft geborgd en welke aanvullende tests nodig zijn.

### [Template NFE](https://ictubeheer.sharepoint.com/:w:/r/teams/Kwaliteitsmanagerssoftwareontwikkeling/Gedeelde%20documenten/General/KA%202.4%20met%20DevOps%20en%20Self-ass%202022/Niet-Functionele-Eisen%20nav%20self-assessment%202022.docx?d=w8e41c4924d2a42b68fe8e7d5f971125f&csf=1&web=1&e=eUDVWu)

- [ ] Aan een PvE te stellen kwaliteitseisen, zoals iedere eis zo ver uitgedetailleerd dat hij aan één partij kan worden toegewezen
- [ ] Expliciet onderscheid maken - ook in de tabellen - tussen NFE's die in de software kunnen worden ingevuld en NFE's die alleen in productie(omgeving) kunnen worden ingevuld.
- [ ] Voorzet voor het proces om te komen tot een overzicht van NFE's
- [x] Geen ICTU-stijl, want het is juist een document van de opdrachtgever, zie #610.

### [Template KwalPlan](https://ictubeheer.sharepoint.com/:w:/r/teams/Kwaliteitsmanagerssoftwareontwikkeling/Gedeelde%20documenten/General/KA%202.4%20met%20DevOps%20en%20Self-ass%202022/Kwaliteitsplan%20v%202.4%20met%20DevOps%20enz.docx?d=w231e7cbcd125438f81a060a0c2d51e9d&csf=1&web=1&e=ZyXgqN)
- [ ] Uitwerken rol van de kwaliteitsmanager bij het opstellen van requirements in de voorfase. Review. Maar belangrijke zaken, zoals verantwoordelijkheid voor NFE-document staat in het PvA, dat soms vertrouwelijk is. Moeten dergelijke zaken (ook) in het KwalPlan komen?
- [x] Uitwerken rol van de kwaliteitsmanager bij het bewaken ervan tijdens de realisatiefase.
Periodieke analyse op het voldoen aan de NFE's die we niet geautomatiseerd kunnen meten, rekening houdend met de in het KP geformuleerde projectspecifieke kwaliteitsmaatregelen. Via bijlage E:
- Eerste regel vervalt
- Na Traceerbaarheid NFE: Periodieke controle met samenvatting van werkwijze KA/M02 hierboven.
- [x] Aanvullen met niet-geautomatiseerde checks. Verwijzing naar Self-assessment en bijlage E (van Dennie) toevoegen in par 5.2
- [x] Aan DoD het voldoen aan de kwaliteitsnormen toevoegen (zoals beschreven in de Kwaliteitsaanpak).

### Self-assessment

- [ ] Specifieker vragen naar het voldoen aan de NFE’s. Bijvoorbeeld door bij M02 te vragen naar hoe invulling is gegeven aan punt KA / M02 hierboven.

**Comment by Sebastiaan127001** [comment]
https://en.wikipedia.org/wiki/Requirement#Characteristics_of_good_requirements

**Comment by Sebastiaan127001** [comment]
https://nl.wikipedia.org/wiki/ISO_25010

**Comment by Sebastiaan127001** [comment]
korte procesbeschrijving toevoegen aan NFE template:
hoe kom je van een PRA tot een lijst NFE's? Welke processtappen doorloop je?
