### ISSUE TITLE
Landscape tabellen in het NFE-document

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#642]
Opties:
- Apart reference.docx
- Oplossen in de code

**Comment by AukeBloembergen** [comment]
Ik heb een proefversie van de hele template in landscape gemaakt. Zie MS Teams: https://ictubeheer.sharepoint.com/:f:/r/teams/ICTUSoftwareontwikkeling2/Gedeelde%20documenten/General/KA%203.1%20(in%20wording)?csf=1&web=1&e=IBJ6K8

Daarin heb ik tbv de leesbaarheid in de standaardteksten de rechtermarge 6 cm laten inspringen.  Om te voorkomen dat de teksten in de tabelcellen ook gaan inspringen kun je daarvoor niet meer de stijl 'Standaard' gebruiken. Daarom heb ik voor de cellen een nieuwe stijl 'St.tekst tabelcel' gemaakt, met de instellingen van de originele stijl 'Standaard'.

Waarom het hele document landscape? Omdat er vrijwel nooit meer wordt geprint en je op een scherm makkelijker een pagina in landscape leest dan in portrait. Daarom schrijven volgens mij steeds meer organisaties hun rapporten in PowerPoint. Maar dan mis je de handigheden van Word.
