### ISSUE TITLE
Overleggen OG toevoegen aan beide PvA-templates

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#675]
Overleggen toevoegen in de paragraaf "Samenwerking" zoals stuurgroepoverleg, architectuuroverleg, projectleidersoverleg, opdrachtgever/opdrachtnemers overleg.

**Comment by AukeBloembergen** [comment]
Mede relevant i.v.m. juiste en tijdige architectuurbeslissingen (gesprek Robert van Wessel)
