### ISSUE TITLE
M02: overweeg "voldoet continu" te vervangen door "bewaakt continu"

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#688]
Projecten kunnen nu eenmaal niet continu aan alle normen voldoen. Denk ook aan technisch schuld.

Als we van M02 "Het project bewaakt continu dat het product aan de kwaliteitsnormen voldoet" maken, ontstaan er vrij veel overlap met M06: "Het project meet kwaliteitsnormen geautomatiseerd en frequent". Het verschil tussen meten en bewaken is nogal subtiel. Bovendien bevat M06 niet zo veel inhoudelijke tekst. We kunnen de tekst van M06 vrij makkelijk integreren in de paragraaf "Realisatiefase: geautomatiseerde kwaliteitsmeting" van M02. M06 zou dan komen te vervallen.

**Comment by AukeBloembergen** [comment]
Wat mij betreft voeren we deze verandering door.
