### ISSUE TITLE
Self-assessment checklist uitbreiden met risicoscore

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#695]
Leid uit de ingevulde checklist af welke van de 10 NPR 5326 risico's maximaal / niet maximaal zijn gemitigeerd op een extra tabblad.

**Comment by AukeBloembergen** [comment]
Goede gelegenheid om de risico's van de NPR te herijken a.h.v. de ervaringen van ICTU (pl's, sdm'ers en km'ers)

**Comment by fniessink** [comment]
Te veel risico op schijnnauwkeurigheid.
