### ISSUE TITLE
M34 5. De broncode kent een gezonde balans tussen isolatie, cohesie en koppeling (6.1),

### ISSUE THREAD

**Issue by ptrr** [ICTU/Kwaliteitsaanpak#705]
Dit is niet SMART. 

Wanneer is het een gezonde balans? 

Issue: er is geen open source tooling die koppeling en cohesie meet voor meerdere programmeertalen.

Mogelijke oplossing: onderhoudbaarheidstoets laten uitvoeren?

Zie ook #860.

**Comment by fniessink** [comment]
Opgelost door toe te voegen aan M34 dat: "Waar nodig scherpt het project, in afstemming met opdrachtgevende organisatie en ontvangende partij, de criteria aan."
