### ISSUE TITLE
M34 6. De broncode heeft een beperkte mate van duplicatie (6.2)

### ISSUE THREAD

**Issue by ptrr** [ICTU/Kwaliteitsaanpak#706]
Een beperkte mate van duplicatie dekt denk ik niet de lading, mijns inzien. Ook niet SMART.

Zou het niet beter zijn om geaccepteerde duplicatie uit te sluiten en daar een formulering. Het is namelijk zeer context afhankelijk.

**Comment by fniessink** [comment]
Opgelost door toe te voegen aan M34 dat: "Waar nodig scherpt het project, in afstemming met opdrachtgevende organisatie en ontvangende partij, de criteria aan."
