### ISSUE TITLE
Colofon - rollen aanscherpen

### ISSUE THREAD

**Issue by AukeBloembergen** [ICTU/Kwaliteitsaanpak#715]
- [x] tabel voor Opsteller(s) toevoegen of combineren met tabel Reviewers of tabel 'Reviewhistorie' (die we beter 'Versiehistorie' kunnen noemen ...)
- [x] expliciet noemen van welke organisatie een rol / functie is (zeker ook in het neutrale template)
- [x] in de tabel bij Functie/rol naast de kwaliteitsmanager ook de sdm'er opnemen
- [x] bij Vereiste goedkeuringen de rol 'Opdrachtgever' toevoegen
- [x] sdm'er toevoegen aan tabel voor reviewers
- [x] rol van de auteur opnemen in Revisietabel

**Comment by bipla2** [comment]
- [ ] punt 1 (tabel voor Opstellers toevoegen of ...): wat is het verschil tussen een Opsteller en een Auteur, onnodig?
- [ ] punt 2 (expliciet noemen welke organisatie een rol/functie is): dit staat er al, onnodig?- [ ]
- [ ] Wat is de toegevoegde waarde van de Status naast een Versienummer? Meestal is een Versie 1.0 definitief. -> Weghalen?

**Comment by bipla2** [comment]
[ICTU-Template-Generiek_715.docx](https://github.com/user-attachments/files/17621189/ICTU-Template-Generiek_715.docx)

**Comment by fniessink** [comment]
[ICTU-Template-Generiek_716.docx](https://github.com/user-attachments/files/17815219/ICTU-Template-Generiek_716.docx)
