### ISSUE TITLE
Template voor separaat document met producten voorfase  

### ISSUE THREAD

**Issue by AukeBloembergen** [ICTU/Kwaliteitsaanpak#760]
Zie MS Teams / ICTU Softwareontwikkeling / Aanbod hulpmiddelen softwareontwikkeling

Waarom?
- Invulling van tip in PvA Voorfase: "Neem bovenstaand overzicht op in een separaat document en gebruik dat in de sprints van de voorfase om bij elke sprintafsluiting de status van de te realiseren producten vast te stellen."
- Bevat voor betrokkenen een compacte toelichting op de verschillende producten, en is daarmee een nuttige leidraad voor het vaststellen van de status.
- Via de kolom 'Urgente informatiebehoefte van dit project' kan de ontwikkelorganisatie prioriteiten aangeven wanneer:
   = niet alle producten op tijd in hun geheel kunnen worden gerealiseerd
   = in een klein project keuzes moeten worden gemaakt over wat wél en wat níet moet worden uitgewerkt.

**Comment by AukeBloembergen** [comment]
Dit template kun je ook positioneren als 'hulpmiddel' ipv onderdeel KA.

**Comment by fniessink** [comment]
@bipla2 gaat behoefte inventariseren.

**Comment by bipla2** [comment]
Behoefte is aanwezig. Wordt in kwaliteitsaanpak opgenomen.
