### ISSUE TITLE
Presentatie KA - bestaan van steeds evoluerende templates vermelden 

### ISSUE THREAD

**Issue by AukeBloembergen** [ICTU/Kwaliteitsaanpak#762]
Kan als vijfde pijler van de KA, of onder een bestaande pijler (zoals Gefaseerd agile of Samenwerking/Wat biedt ICTU?). Incl. toelichting op:
- 80-80-regel
- evoluerend: o.b.v. ervaringen in de projecten en van self-assessments

NB. Waarom niet beschikbaar op ictu.nl?

"Een deel van de templates is een service voor onze opdrachtgevers" (Birgitte)

Tasks:
- Basispresentatieslides opnemen in gegenereerde presentatie over KA
- Vijfde pijler toevoegen
- Slides met maatregelen verplaatsen naar "sectie bijlage"

**Comment by fniessink** [comment]
De presentatie die je bedoelt wordt niet gegenereerd. De presentatie die we wel genereren bevat nu alleen de titels en korte beschrijvingen van de maatregelen. Zie https://ictu.github.io/Kwaliteitsaanpak/. Het zou goed zijn om beiden samen te voegen, maar dat is wel een flinke klus.

**Comment by AukeBloembergen** [comment]
Weet ik. Maar ik zocht een plaats om updates aan de presentatie met je te delen. Zal ik een voorzet doen (na mijn reis)?

**Comment by AukeBloembergen** [comment]
Frank en Birgitte, de discussie waaraan behoefte is laat ik over aan jullie.
