### ISSUE TITLE
Aanpassen hoofdstuk 8 beveiligbaarheid in template NFE

### ISSUE THREAD

**Issue by MaxStaallekker** [ICTU/Kwaliteitsaanpak#841]
Momenteel zijn in het NFE template beveiligingseisen opgenomen niet die niet direct te relateren zijn aan de BIO, SSD of ISO. De vraag is waar deze vandaan komen, waarom deze geen verwijzing bevatten naar de betreffende norm en het template misschien niet specifieke normen uit de BIO, SSD, ASVS, OWASP top 10 o.i.d. zou moeten bevatten incl. verwijzing.

Gewenst is om specifieke normen op te nemen die als NFE kunnen gelden in het hoofdstuk beveiligbaarheid.

**Comment by AukeBloembergen** [comment]
Par 8.1 nog aanvullen met 'realisatie in' en 'realisatie door'. Is in alle andere onderdelen al gebeurd.

**Comment by AukeBloembergen** [comment]
Landscape-versie maken? Of Excel-overzicht?
