### ISSUE TITLE
Index toevoegen aan de HTML-versie van de Kwaliteitsaanpak 

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/Kwaliteitsaanpak#859]
Het zou handig zijn als er een index was op de [HTML-versie van de Kwaliteitsaanpak](https://ictu.github.io/Kwaliteitsaanpak/v3.0.1/ICTU-Kwaliteitsaanpak.html). Deze moet dan links bevatten zodat je direct naar de juiste maatregel kunt springen.

**Comment by Sebastiaan127001** [comment]
De [HTML-pagina](https://ictu.github.io/Kwaliteitsaanpak/v4.0.0/ICTU-Kwaliteitsaanpak.html) zou een index moeten hebben met klikbare links direct naar de maatregelen.
Zo kan ik ook direct verwijzen naar een maatregel door bijvoorbeeld

https://ictu.github.io/Kwaliteitsaanpak/v4.0.0/ICTU-Kwaliteitsaanpak.html#m34

(dit laatste kan nu al, maar daarvoor moet je wel de broncode inspecteren of je moet het weten.)

**Comment by fniessink** [comment]
De onderhanden (en dus volgende) versie van de KA heeft dit, zie: https://ictu.github.io/Kwaliteitsaanpak/wip/ICTU-Kwaliteitsaanpak.html
