### ISSUE TITLE
Afspraken maken over monitoring nieuwe kwetsbaarheden

### ISSUE THREAD

**Issue by fniessink** [ICTU/Kwaliteitsaanpak#963]
Na een release van de software kunnen er nieuwe kwetsbaarheden worden ontdekt in de gebruikte bibliotheken. Opdrachtgever en ICTU moeten afspreken wie er verantwoordelijk is voor het opmerken van deze nieuwe kwetsbaarheden en hoe deze eventueel gefixt worden. Dit punt opnemen in PvA-realisatiefase-template.

**Comment by bipla2** [comment]
[[963-ICTU-Template-Plan-van-Aanpak-Realisatiefase.docx](https://github.com/user-attachments/files/17918346/963-ICTU-Template-Plan-van-Aanpak-Realisatiefase.docx)
](url)

**Comment by bipla2** [comment]
@fniessink : voorstel toegevoegd.
